// This file is auto-generated by @hey-api/openapi-ts

import type { ApiHealthCheckResponse2 } from './types.gen';

const apiHealthCheckResponseSchemaResponseTransformer = (data: any) => {
    data.health = apiHostHealthSchemaResponseTransformer(data.health);
    return data;
};

const apiHostHealthSchemaResponseTransformer = (data: any) => {
    data.version = hostVersionsSchemaResponseTransformer(data.version);
    return data;
};

const hostVersionsSchemaResponseTransformer = (data: any) => {
    data.productVersion = hostDeploymentVersionSchemaResponseTransformer(data.productVersion);
    return data;
};

const hostDeploymentVersionSchemaResponseTransformer = (data: any) => {
    if (data.deployed) {
        data.deployed = new Date(data.deployed);
    }
    return data;
};

export const apiHealthCheckResponseTransformer = async (data: any): Promise<ApiHealthCheckResponse2> => {
    data = apiHealthCheckResponseSchemaResponseTransformer(data);
    return data;
};
