//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationsInfrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrganizationsInfrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Role&apos; is invalid.
        /// </summary>
        internal static string AssignRolesToOrganizationRequestValidator_InvalidRole {
            get {
                return ResourceManager.GetString("AssignRolesToOrganizationRequestValidator_InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Roles&apos; is either empty or contains invalid roles.
        /// </summary>
        internal static string AssignRolesToOrganizationRequestValidator_InvalidRoles {
            get {
                return ResourceManager.GetString("AssignRolesToOrganizationRequestValidator_InvalidRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Field&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchConditionSchemaValidator_InvalidField {
            get {
                return ResourceManager.GetString("BranchConditionSchemaValidator_InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Value&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchConditionSchemaValidator_InvalidValue {
            get {
                return ResourceManager.GetString("BranchConditionSchemaValidator_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Condition&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchSchemaValidator_InvalidCondition {
            get {
                return ResourceManager.GetString("BranchSchemaValidator_InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchSchemaValidator_InvalidId {
            get {
                return ResourceManager.GetString("BranchSchemaValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Label&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchSchemaValidator_InvalidLabel {
            get {
                return ResourceManager.GetString("BranchSchemaValidator_InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;NextStepId&apos; is either missing or invalid.
        /// </summary>
        internal static string BranchSchemaValidator_InvalidNextStepId {
            get {
                return ResourceManager.GetString("BranchSchemaValidator_InvalidNextStepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Name&apos; is invalid.
        /// </summary>
        internal static string ChangeOrganizationRequestValidator_InvalidName {
            get {
                return ResourceManager.GetString("ChangeOrganizationRequestValidator_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Name&apos; is either missing or invalid.
        /// </summary>
        internal static string CreateOrganizationRequestValidator_InvalidName {
            get {
                return ResourceManager.GetString("CreateOrganizationRequestValidator_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Workflow&apos; is either missing or invalid.
        /// </summary>
        internal static string InitiateOnboardingWorkflowRequestValidator_InvalidWorkflow {
            get {
                return ResourceManager.GetString("InitiateOnboardingWorkflowRequestValidator_InvalidWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &apos;Email&apos; or the &apos;UserId&apos; can be provided, not both.
        /// </summary>
        internal static string InviteOrganizationMemberRequestValidator_BothUserIdAndEmail {
            get {
                return ResourceManager.GetString("InviteOrganizationMemberRequestValidator_BothUserIdAndEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; is either missing or invalid.
        /// </summary>
        internal static string InviteOrganizationMemberRequestValidator_InvalidUserEmail {
            get {
                return ResourceManager.GetString("InviteOrganizationMemberRequestValidator_InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the &apos;Email&apos; and &apos;UserId&apos; are missing.
        /// </summary>
        internal static string InviteOrganizationMemberRequestValidator_MissingUserIdAndEmail {
            get {
                return ResourceManager.GetString("InviteOrganizationMemberRequestValidator_MissingUserIdAndEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;NextStepId&apos; is invalid.
        /// </summary>
        internal static string MoveToWorkflowStepRequestValidator_InvalidNextStepId {
            get {
                return ResourceManager.GetString("MoveToWorkflowStepRequestValidator_InvalidNextStepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &apos;{0}&apos; branch &apos;{1}&apos; cannot reference a non-existent step &apos;{2}&apos; as next step.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_AnyBranchNextStepUndefined {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_AnyBranchNextStepUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &apos;{0}&apos; cannot reference a non-existent step &apos;{1}&apos; as next step.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_AnyStepNextStepUndefined {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_AnyStepNextStepUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow contains a cycle involving step &apos;{0}&apos;.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_CycleDetected {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_CycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End step &apos;{0}&apos; cannot have a next step or branches.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_EndStepHasOutgoingEdges {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_EndStepHasOutgoingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End step &apos;{0}&apos; must have a weight of 0, but has weight {1}.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_EndStepMustHaveZeroWeight {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_EndStepMustHaveZeroWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear workflow (without branches) must have a total weight of 100, but has total weight {0}.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_LinearWorkflowWeightMustBe100 {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_LinearWorkflowWeightMustBe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow can only have one &apos;End&apos; node, found: {0}.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_MultipleEndNodes {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_MultipleEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow can only have one &apos;Start&apos; node, found: {0}.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_MultipleStartNodes {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_MultipleStartNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start step &apos;{0}&apos; cannot be referenced by other steps.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_StartStepHasIncomingEdges {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_StartStepHasIncomingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &apos;{0}&apos; has no path to the &apos;End&apos; step.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_StepCannotReachEnd {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_StepCannotReachEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &apos;{0}&apos; is not reachable on any path from the start step.
        /// </summary>
        internal static string OnboardingWorkflowGraphService_Validate_StepNotReachableFromStart {
            get {
                return ResourceManager.GetString("OnboardingWorkflowGraphService_Validate_StepNotReachableFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; is either missing or invalid.
        /// </summary>
        internal static string StepSchemaValidator_InvalidId {
            get {
                return ResourceManager.GetString("StepSchemaValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;NextStepId&apos; is invalid.
        /// </summary>
        internal static string StepSchemaValidator_InvalidNextStepId {
            get {
                return ResourceManager.GetString("StepSchemaValidator_InvalidNextStepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Title&apos; is either missing or invalid.
        /// </summary>
        internal static string StepSchemaValidator_InvalidTitle {
            get {
                return ResourceManager.GetString("StepSchemaValidator_InvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Weight&apos; must be between 0 and 100.
        /// </summary>
        internal static string StepSchemaValidator_InvalidWeight {
            get {
                return ResourceManager.GetString("StepSchemaValidator_InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Values&apos; is either missing or empty.
        /// </summary>
        internal static string UpdateCurrentWorkflowStepRequestValidator_InvalidValues {
            get {
                return ResourceManager.GetString("UpdateCurrentWorkflowStepRequestValidator_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;EndStepId&apos; is either missing or invalid.
        /// </summary>
        internal static string WorkflowSchemaValidator_InvalidEndStepId {
            get {
                return ResourceManager.GetString("WorkflowSchemaValidator_InvalidEndStepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Name&apos; is either missing or invalid.
        /// </summary>
        internal static string WorkflowSchemaValidator_InvalidName {
            get {
                return ResourceManager.GetString("WorkflowSchemaValidator_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;StartStepId&apos; is either missing or invalid.
        /// </summary>
        internal static string WorkflowSchemaValidator_InvalidStartStepId {
            get {
                return ResourceManager.GetString("WorkflowSchemaValidator_InvalidStartStepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Steps&apos; is either missing or empty.
        /// </summary>
        internal static string WorkflowSchemaValidator_InvalidSteps {
            get {
                return ResourceManager.GetString("WorkflowSchemaValidator_InvalidSteps", resourceCulture);
            }
        }
    }
}
