// This file is auto-generated by @hey-api/openapi-ts

import type { AuthenticateCredentialResponse, AuthenticateSingleSignOnResponse, CancelSubscriptionResponse, ChangeSubscriptionPlanPatchResponse, ChangeSubscriptionPlanPutResponse, ConfirmCredentialMfaAuthenticatorForCallerPatchResponse, ConfirmCredentialMfaAuthenticatorForCallerPutResponse, ForceCancelSubscriptionResponse, FormatsTestingOnlyResponse2, GetOAuth2ClientResponse2, GetSubscriptionResponse2, MakeBookingResponse2, RefreshTokenResponse2, RegenerateOAuth2ClientSecretResponse2, RegisterMachineResponse2, SearchAllApiKeysForCallerResponse, SearchAllAuditsResponse2, SearchAllBookingsResponse2, SearchAllEmailDeliveriesResponse2, SearchAllSmsDeliveriesResponse2, SearchSubscriptionHistoryResponse2, TransferSubscriptionPatchResponse, TransferSubscriptionPutResponse, VerifyCredentialMfaAuthenticatorForCallerPatchResponse, VerifyCredentialMfaAuthenticatorForCallerPutResponse } from './types.gen';

const searchAllApiKeysResponseSchemaResponseTransformer = (data: any) => {
    data.keys = data.keys.map((item: any) => apiKeySchemaResponseTransformer(item));
    return data;
};

const apiKeySchemaResponseTransformer = (data: any) => {
    if (data.expiresOnUtc) {
        data.expiresOnUtc = new Date(data.expiresOnUtc);
    }
    return data;
};

export const searchAllApiKeysForCallerResponseTransformer = async (data: any): Promise<SearchAllApiKeysForCallerResponse> => {
    data = searchAllApiKeysResponseSchemaResponseTransformer(data);
    return data;
};

const searchAllAuditsResponseSchemaResponseTransformer = (data: any) => {
    data.audits = data.audits.map((item: any) => auditSchemaResponseTransformer(item));
    return data;
};

const auditSchemaResponseTransformer = (data: any) => {
    data.created = new Date(data.created);
    return data;
};

export const searchAllAuditsResponseTransformer = async (data: any): Promise<SearchAllAuditsResponse2> => {
    data = searchAllAuditsResponseSchemaResponseTransformer(data);
    return data;
};

const refreshTokenResponseSchemaResponseTransformer = (data: any) => {
    data.tokens = authenticateTokensSchemaResponseTransformer(data.tokens);
    return data;
};

const authenticateTokensSchemaResponseTransformer = (data: any) => {
    data.accessToken = authenticationTokenSchemaResponseTransformer(data.accessToken);
    if (data.idToken) {
        data.idToken = authenticationTokenSchemaResponseTransformer(data.idToken);
    }
    data.refreshToken = authenticationTokenSchemaResponseTransformer(data.refreshToken);
    return data;
};

const authenticationTokenSchemaResponseTransformer = (data: any) => {
    if (data.expiresOn) {
        data.expiresOn = new Date(data.expiresOn);
    }
    return data;
};

export const refreshTokenResponseTransformer = async (data: any): Promise<RefreshTokenResponse2> => {
    data = refreshTokenResponseSchemaResponseTransformer(data);
    return data;
};

const searchAllBookingsResponseSchemaResponseTransformer = (data: any) => {
    data.bookings = data.bookings.map((item: any) => bookingSchemaResponseTransformer(item));
    return data;
};

const bookingSchemaResponseTransformer = (data: any) => {
    data.endUtc = new Date(data.endUtc);
    data.startUtc = new Date(data.startUtc);
    return data;
};

export const searchAllBookingsResponseTransformer = async (data: any): Promise<SearchAllBookingsResponse2> => {
    data = searchAllBookingsResponseSchemaResponseTransformer(data);
    return data;
};

const makeBookingResponseSchemaResponseTransformer = (data: any) => {
    data.booking = bookingSchemaResponseTransformer(data.booking);
    return data;
};

export const makeBookingResponseTransformer = async (data: any): Promise<MakeBookingResponse2> => {
    data = makeBookingResponseSchemaResponseTransformer(data);
    return data;
};

const getOAuth2ClientWithSecretsResponseSchemaResponseTransformer = (data: any) => {
    data.client = oAuth2ClientWithSecretsSchemaResponseTransformer(data.client);
    return data;
};

const oAuth2ClientWithSecretsSchemaResponseTransformer = (data: any) => {
    data.secrets = data.secrets.map((item: any) => oAuthClientSecretSchemaResponseTransformer(item));
    return data;
};

const oAuthClientSecretSchemaResponseTransformer = (data: any) => {
    if (data.expiresOnUtc) {
        data.expiresOnUtc = new Date(data.expiresOnUtc);
    }
    return data;
};

export const getOAuth2ClientResponseTransformer = async (data: any): Promise<GetOAuth2ClientResponse2> => {
    data = getOAuth2ClientWithSecretsResponseSchemaResponseTransformer(data);
    return data;
};

const regenerateOAuth2ClientSecretResponseSchemaResponseTransformer = (data: any) => {
    data.client = oAuth2ClientWithSecretSchemaResponseTransformer(data.client);
    return data;
};

const oAuth2ClientWithSecretSchemaResponseTransformer = (data: any) => {
    if (data.expiresOnUtc) {
        data.expiresOnUtc = new Date(data.expiresOnUtc);
    }
    return data;
};

export const regenerateOAuth2ClientSecretResponseTransformer = async (data: any): Promise<RegenerateOAuth2ClientSecretResponse2> => {
    data = regenerateOAuth2ClientSecretResponseSchemaResponseTransformer(data);
    return data;
};

const authenticateResponseSchemaResponseTransformer = (data: any) => {
    data.tokens = authenticateTokensSchemaResponseTransformer(data.tokens);
    return data;
};

export const authenticateCredentialResponseTransformer = async (data: any): Promise<AuthenticateCredentialResponse> => {
    data = authenticateResponseSchemaResponseTransformer(data);
    return data;
};

const searchAllEmailDeliveriesResponseSchemaResponseTransformer = (data: any) => {
    data.emails = data.emails.map((item: any) => deliveredEmailSchemaResponseTransformer(item));
    return data;
};

const deliveredEmailSchemaResponseTransformer = (data: any) => {
    data.attempts = data.attempts.map((item: any) => {
        new Date(item);
        return item;
    });
    data.created = new Date(data.created);
    if (data.deliveredAt) {
        data.deliveredAt = new Date(data.deliveredAt);
    }
    if (data.failedDeliveryAt) {
        data.failedDeliveryAt = new Date(data.failedDeliveryAt);
    }
    if (data.sentAt) {
        data.sentAt = new Date(data.sentAt);
    }
    return data;
};

export const searchAllEmailDeliveriesResponseTransformer = async (data: any): Promise<SearchAllEmailDeliveriesResponse2> => {
    data = searchAllEmailDeliveriesResponseSchemaResponseTransformer(data);
    return data;
};

const registerMachineResponseSchemaResponseTransformer = (data: any) => {
    data.machine = machineCredentialSchemaResponseTransformer(data.machine);
    return data;
};

const machineCredentialSchemaResponseTransformer = (data: any) => {
    if (data.expiresOnUtc) {
        data.expiresOnUtc = new Date(data.expiresOnUtc);
    }
    return data;
};

export const registerMachineResponseTransformer = async (data: any): Promise<RegisterMachineResponse2> => {
    data = registerMachineResponseSchemaResponseTransformer(data);
    return data;
};

const confirmCredentialMfaAuthenticatorForCallerResponseSchemaResponseTransformer = (data: any) => {
    data.tokens = authenticateTokensSchemaResponseTransformer(data.tokens);
    return data;
};

export const confirmCredentialMfaAuthenticatorForCallerPatchResponseTransformer = async (data: any): Promise<ConfirmCredentialMfaAuthenticatorForCallerPatchResponse> => {
    data = confirmCredentialMfaAuthenticatorForCallerResponseSchemaResponseTransformer(data);
    return data;
};

export const confirmCredentialMfaAuthenticatorForCallerPutResponseTransformer = async (data: any): Promise<ConfirmCredentialMfaAuthenticatorForCallerPutResponse> => {
    data = confirmCredentialMfaAuthenticatorForCallerResponseSchemaResponseTransformer(data);
    return data;
};

export const verifyCredentialMfaAuthenticatorForCallerPatchResponseTransformer = async (data: any): Promise<VerifyCredentialMfaAuthenticatorForCallerPatchResponse> => {
    data = authenticateResponseSchemaResponseTransformer(data);
    return data;
};

export const verifyCredentialMfaAuthenticatorForCallerPutResponseTransformer = async (data: any): Promise<VerifyCredentialMfaAuthenticatorForCallerPutResponse> => {
    data = authenticateResponseSchemaResponseTransformer(data);
    return data;
};

export const authenticateSingleSignOnResponseTransformer = async (data: any): Promise<AuthenticateSingleSignOnResponse> => {
    data = authenticateResponseSchemaResponseTransformer(data);
    return data;
};

const searchAllSmsDeliveriesResponseSchemaResponseTransformer = (data: any) => {
    data.smses = data.smses.map((item: any) => deliveredSmsSchemaResponseTransformer(item));
    return data;
};

const deliveredSmsSchemaResponseTransformer = (data: any) => {
    data.attempts = data.attempts.map((item: any) => {
        new Date(item);
        return item;
    });
    data.created = new Date(data.created);
    if (data.deliveredAt) {
        data.deliveredAt = new Date(data.deliveredAt);
    }
    if (data.failedDeliveryAt) {
        data.failedDeliveryAt = new Date(data.failedDeliveryAt);
    }
    if (data.sentAt) {
        data.sentAt = new Date(data.sentAt);
    }
    return data;
};

export const searchAllSmsDeliveriesResponseTransformer = async (data: any): Promise<SearchAllSmsDeliveriesResponse2> => {
    data = searchAllSmsDeliveriesResponseSchemaResponseTransformer(data);
    return data;
};

const getSubscriptionResponseSchemaResponseTransformer = (data: any) => {
    data.subscription = subscriptionWithPlanSchemaResponseTransformer(data.subscription);
    return data;
};

const subscriptionWithPlanSchemaResponseTransformer = (data: any) => {
    if (data.canceledDateUtc) {
        data.canceledDateUtc = new Date(data.canceledDateUtc);
    }
    data.invoice = invoiceSummarySchemaResponseTransformer(data.invoice);
    data.paymentMethod = subscriptionPaymentMethodSchemaResponseTransformer(data.paymentMethod);
    data.plan = subscriptionPlanSchemaResponseTransformer(data.plan);
    return data;
};

const invoiceSummarySchemaResponseTransformer = (data: any) => {
    if (data.nextUtc) {
        data.nextUtc = new Date(data.nextUtc);
    }
    return data;
};

const subscriptionPaymentMethodSchemaResponseTransformer = (data: any) => {
    if (data.expiresOn) {
        data.expiresOn = new Date(data.expiresOn);
    }
    return data;
};

const subscriptionPlanSchemaResponseTransformer = (data: any) => {
    if (data.trialEndDateUtc) {
        data.trialEndDateUtc = new Date(data.trialEndDateUtc);
    }
    return data;
};

export const cancelSubscriptionResponseTransformer = async (data: any): Promise<CancelSubscriptionResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

export const getSubscriptionResponseTransformer = async (data: any): Promise<GetSubscriptionResponse2> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

export const changeSubscriptionPlanPatchResponseTransformer = async (data: any): Promise<ChangeSubscriptionPlanPatchResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

export const changeSubscriptionPlanPutResponseTransformer = async (data: any): Promise<ChangeSubscriptionPlanPutResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

export const forceCancelSubscriptionResponseTransformer = async (data: any): Promise<ForceCancelSubscriptionResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

const searchSubscriptionHistoryResponseSchemaResponseTransformer = (data: any) => {
    data.invoices = data.invoices.map((item: any) => invoiceSchemaResponseTransformer(item));
    return data;
};

const invoiceSchemaResponseTransformer = (data: any) => {
    if (data.invoicedOnUtc) {
        data.invoicedOnUtc = new Date(data.invoicedOnUtc);
    }
    if (data.payment) {
        data.payment = invoiceItemPaymentSchemaResponseTransformer(data.payment);
    }
    if (data.periodEndUtc) {
        data.periodEndUtc = new Date(data.periodEndUtc);
    }
    if (data.periodStartUtc) {
        data.periodStartUtc = new Date(data.periodStartUtc);
    }
    return data;
};

const invoiceItemPaymentSchemaResponseTransformer = (data: any) => {
    if (data.paidOnUtc) {
        data.paidOnUtc = new Date(data.paidOnUtc);
    }
    return data;
};

export const searchSubscriptionHistoryResponseTransformer = async (data: any): Promise<SearchSubscriptionHistoryResponse2> => {
    data = searchSubscriptionHistoryResponseSchemaResponseTransformer(data);
    return data;
};

export const transferSubscriptionPatchResponseTransformer = async (data: any): Promise<TransferSubscriptionPatchResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

export const transferSubscriptionPutResponseTransformer = async (data: any): Promise<TransferSubscriptionPutResponse> => {
    data = getSubscriptionResponseSchemaResponseTransformer(data);
    return data;
};

const formatsTestingOnlyResponseSchemaResponseTransformer = (data: any) => {
    data.custom = customDtoSchemaResponseTransformer(data.custom);
    if (data.time) {
        data.time = new Date(data.time);
    }
    return data;
};

const customDtoSchemaResponseTransformer = (data: any) => {
    if (data.time) {
        data.time = new Date(data.time);
    }
    return data;
};

export const formatsTestingOnlyResponseTransformer = async (data: any): Promise<FormatsTestingOnlyResponse2> => {
    data = formatsTestingOnlyResponseSchemaResponseTransformer(data);
    return data;
};
