//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is invalid.
        /// </summary>
        internal static string Avatar_InvalidUrl {
            get {
                return ResourceManager.GetString("Avatar_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount is invalid.
        /// </summary>
        internal static string BillingInvoice_InvalidAmount {
            get {
                return ResourceManager.GetString("BillingInvoice_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency must be positive.
        /// </summary>
        internal static string BillingPeriod_InvalidFrequency {
            get {
                return ResourceManager.GetString("BillingPeriod_InvalidFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of the provider is empty or invalid.
        /// </summary>
        internal static string BillingProvider_InvalidMetadata {
            get {
                return ResourceManager.GetString("BillingProvider_InvalidMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the provider is not invalid.
        /// </summary>
        internal static string BillingProvider_InvalidName {
            get {
                return ResourceManager.GetString("BillingProvider_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr or Mrs.
        /// </summary>
        internal static string EmailAddress_FallbackGuessedFirstName {
            get {
                return ResourceManager.GetString("EmailAddress_FallbackGuessedFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is not a valid email address.
        /// </summary>
        internal static string EmailAddress_InvalidAddress {
            get {
                return ResourceManager.GetString("EmailAddress_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email Domain is not valid.
        /// </summary>
        internal static string EmailDomain_InvalidDomain {
            get {
                return ResourceManager.GetString("EmailDomain_InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feature value is invalid.
        /// </summary>
        internal static string Features_InvalidFeature {
            get {
                return ResourceManager.GetString("Features_InvalidFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Locale is invalid.
        /// </summary>
        internal static string Locale_InvalidLocale {
            get {
                return ResourceManager.GetString("Locale_InvalidLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name is invalid.
        /// </summary>
        internal static string Name_InvalidName {
            get {
                return ResourceManager.GetString("Name_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PhoneNumber value is not a valid international phone number.
        /// </summary>
        internal static string PhoneNumber_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanId is empty.
        /// </summary>
        internal static string ProviderPlan_InvalidPlanId {
            get {
                return ResourceManager.GetString("ProviderPlan_InvalidPlanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionReference is empty.
        /// </summary>
        internal static string ProviderSubscription_InvalidSubscriptionReference {
            get {
                return ResourceManager.GetString("ProviderSubscription_InvalidSubscriptionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Role value is invalid.
        /// </summary>
        internal static string Roles_InvalidRole {
            get {
                return ResourceManager.GetString("Roles_InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list of strings contains value &apos;{0}&apos;, but its value is null.
        /// </summary>
        internal static string StringNameValues_InvalidValue {
            get {
                return ResourceManager.GetString("StringNameValues_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Timezone value is invalid.
        /// </summary>
        internal static string Timezone_InvalidTimezone {
            get {
                return ResourceManager.GetString("Timezone_InvalidTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one event has the same ID as another.
        /// </summary>
        internal static string TrialEventSchedule_DuplicateEvents {
            get {
                return ResourceManager.GetString("TrialEventSchedule_DuplicateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay cannot be negative.
        /// </summary>
        internal static string TrialScheduleEvent_InvalidDelay {
            get {
                return ResourceManager.GetString("TrialScheduleEvent_InvalidDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is invalid.
        /// </summary>
        internal static string TrialScheduleEvent_InvalidId {
            get {
                return ResourceManager.GetString("TrialScheduleEvent_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial is already converted.
        /// </summary>
        internal static string TrialTimeline_AlreadyConverted {
            get {
                return ResourceManager.GetString("TrialTimeline_AlreadyConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial is already expired.
        /// </summary>
        internal static string TrialTimeline_AlreadyExpired {
            get {
                return ResourceManager.GetString("TrialTimeline_AlreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial is not past due date to expire.
        /// </summary>
        internal static string TrialTimeline_ExpiryNotDue {
            get {
                return ResourceManager.GetString("TrialTimeline_ExpiryNotDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial duration must be greater than zero days.
        /// </summary>
        internal static string TrialTimeline_InvalidDuration {
            get {
                return ResourceManager.GetString("TrialTimeline_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial cannot start in the future.
        /// </summary>
        internal static string TrialTimeline_StartsAtInFuture {
            get {
                return ResourceManager.GetString("TrialTimeline_StartsAtInFuture", resourceCulture);
            }
        }
    }
}
