services:
  # See https://hub.docker.com/r/localstack/localstack
  localstack:
    image: localstack/localstack:stable
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # See https://hub.docker.com/r/microsoft/mssql-server
  # Guide: https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
  mssql:
    build: ./images/mssql-custom
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      # Database initialization scripts which will be run on container startup
      - ./init-scripts/mssql:/docker-entrypoint-initdb.d
  
  # See https://hub.docker.com/r/eventstore/eventstore
  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      # Needed for the stream browser feature in Admin UI
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore
      - eventstore-logs:/var/log/eventstore
  
  # See https://hub.docker.com/r/microsoft/azure-storage-azurite
  # Guide: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "${AZURITE_VOLUME_DIR:-./volume/azurite}:/data"

volumes:
  eventstore-data:
  eventstore-logs:
  mssql-data: